### ISSUE TITLE
Persistent App Crashing after Download Completes

### ISSUE THREAD

**Issue by jonmacchio** [nicoSWD/put.io-adder#10]
Hi,

Every completed download causes the app to crash, consistent report from console shows this:

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x7fff7a4b9240'
abort() called
terminating with uncaught exception of type NSException'
```

Otherwise app is running fantastically!

**Comment by nicoSWD** [comment]
Hey y'all!

Sorry for the late response. Please give the last release a try, which attempts to fix this issue.

https://github.com/nicoSWD/put.io-adder/releases/tag/v2.9

Let me know if this works for you!

Thanks!

**Comment by rc1** [comment]
Thanks for this. No problems so far. Like the status bar progress icon.

**Comment by nicoSWD** [comment]
Thanks! :) I'm glad to hear that.

Please let me know if you run into trouble with the latest release.

**Comment by gmogames** [comment]
Yep, Working fine for me as well. really nice :)

**Comment by nicoSWD** [comment]
Awesome! Going to close this, then.

Please feel free to reopen the issue if the app crashes again.

Thanks!
