### ISSUE TITLE
All torrents failing because of duplicate

### ISSUE THREAD

**Issue by matthewbarram** [nicoSWD/put.io-adder#11]
Hi 

Whenever I add a torrent (open file with app) I can get a message saying that it is a duplicate.

I am running version 2.8 (455) - http://cl.ly/image/2q0E2F2K1f0d/Screen%20Shot%202014-10-25%20at%206.13.42%20pm.png

Cheers
Matthew

**Comment by threespoons** [comment]
I am also having this problem, this is causing a real issue for my automated set up :-(

**Comment by mjw56** [comment]
I'm getting the same thing. How can I fix this?

**Comment by nicoSWD** [comment]
Hey y'all!

Sorry for the late response. Please give the last release a try, which attempts to fix this issue.

https://github.com/nicoSWD/put.io-adder/releases/tag/v2.9

Let me know if this works for you!

Thanks!

**Comment by mjw56** [comment]
@nicoSWD hey! your fix is working for me. 

much obliged!! cheers! :D

**Comment by nicoSWD** [comment]
Thanks for letting me know! :)

I'll close this issue or now.
