### ISSUE TITLE
App goes for about 3 minutes, then dies.

### ISSUE THREAD

**Issue by bdmorin** [nicoSWD/put.io-adder#12]
http://hastebin.com/eyojovoceq

![screen shot 2015-03-20 at 21 08 04](https://cloud.githubusercontent.com/assets/476219/6763332/4df3dbce-cf45-11e4-877c-56d77c3d2910.png)

If i just leave it running it dies. Not complaining, it still works. Just not sure if it's happening to anyone else.

**Comment by nicoSWD** [comment]
Thank you!

Does it crash after a transfer completes, or just randomly?

**Comment by bdmorin** [comment]
Completely randomly. Usually is only after l like 3-5 minutes

**Comment by nicoSWD** [comment]
Hi @bdmorin,

are you still facing the same issue?

**Comment by bdmorin** [comment]
Negative, the update after i opened the issue made it go away!

**Comment by nicoSWD** [comment]
Excellent! Thanks for letting me know! I can close this issue, then!

👍
