### ISSUE TITLE
How do I make put.io-adder default .torrent file handler? 

### ISSUE THREAD

**Issue by zzztimbo** [nicoSWD/put.io-adder#13]
I've tried to edit the following file. It doesn't exist.
~/Library/Preferences/com.apple.LaunchServices.plist

**Comment by nicoSWD** [comment]
Hi,

looks like at some point, Apple decided to move the file to this location:

`~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist`

However, it's probably easier if you right click a `.torrent` file, click on `Get Info`, and then, in the `Open with` Section, select `Put.io Adder`, and then finally click on `Change All...`

Thanks for using Put.io Adder! :)

**Comment by zzztimbo** [comment]
Thanks. I modified the plist to make put.io-adder the default handler for magnet links. The right click on .torrent file also worked too.

**Comment by nicoSWD** [comment]
Awesome, thanks for the feedback! 👍 Glad you got this resolved.

Closing the issue.
