### ISSUE TITLE
XSPF direct VLC stream

### ISSUE THREAD

**Issue by jorgenbs** [nicoSWD/put.io-adder#16]
The new Put.io has a way of getting .xspf files for VLC streaming. It works pretty well and it would be nice if you could double-click a file and based on your preference go open it directly in VLC.

The URI pattern is put.io/files/{file_id}/xspf

**Comment by nicoSWD** [comment]
Thank you!

I actually have a beta version laying around here which enables streaming for some files by right clicking them in the app. The approach I've taken only works with certain files, though, so this could be quite useful. I will look into this.

Thanks!

**Comment by nicoSWD** [comment]
So I decided to get my shit together, and finish version 3 of the app. And here it is:

https://github.com/nicoSWD/put.io-adder/releases/tag/v3.0

I couldn't find a way to get the XSPF via the API, but I think I've found a reliable way to stream videos through VLC. There are a few issues, though. The app only shows transfers, and the downloaded files may be inside a folder. The app is currently unable to stream those.

Please give it a shot and let me know if it works for you.

Thanks again!

**Comment by jorgenbs** [comment]
Cool! I Installed it.
Too bad that you couldn't do XSPF via the API. In my experience most of the
stuff I download are in folders, and since the app doesn't know what it can
and cannot stream I'm not finding that I'm saving much time trying to
direct-stream it with a high fail-rate.
I tweeted them about plans on implementing xspf to the api, so we'll see :)

On Sat, May 21, 2016 at 10:02 AM, Nico Oelgart <notifications@github.com>
wrote:

> So I decided to get my shit together, and finish version 3 of the app. And
> here it is:
>
> https://github.com/nicoSWD/put.io-adder/releases/tag/v3.0
>
> I couldn't find a way to get the XSPF via the API, but I think I've found
> a reliable way to stream videos through VLC. There are a few issues,
> though. The app only shows transfers, and the downloaded files may be
> inside a folder. The app is currently unable to stream those.
>
> Please give it a shot and let me know if it works for you.
>
> Thanks again!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nicoSWD/put.io-adder/issues/16#issuecomment-220744973>
>



-- 
Jørgen Bøe Svendsen

**Comment by nicoSWD** [comment]
Good news!! I just figured out that you can access the XSPF URL by just passing it the OAuth token. 😀

Update coming today!

Thanks for your contribution. This makes the app a million times more awesome!

**Comment by jorgenbs** [comment]
Awesome! Also got a reply from put.io
https://twitter.com/putdotio/status/733930750752522240

On Sat, May 21, 2016 at 7:37 PM, Nico Oelgart <notifications@github.com>
wrote:

> Good news!! I just figured out that you can access the XSPF URL by just
> passing it the OAuth token. 😀
>
> Update coming today!
>
> Thanks for your contribution. This makes the app a million times more
> awesome!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nicoSWD/put.io-adder/issues/16#issuecomment-220768550>
>



-- 
Jørgen Bøe Svendsen
