### ISSUE TITLE
Feature request: option to disable beep after transfer completes.

### ISSUE THREAD

**Issue by joshkerr** [nicoSWD/put.io-adder#20]
I don't want that annoying beep after a torrent completes.

**Comment by nicoSWD** [comment]
Hehe, I think that's configurable in System Preferences -> Notifications. You should be able to change the sound settings there. I haven't tested this, but I think it should work.

![screen shot 2016-08-04 at 00 10 46](https://cloud.githubusercontent.com/assets/205852/17383760/027074f4-59d8-11e6-98f1-d6ec3671de9a.png)

**Comment by joshkerr** [comment]
Yes. That fixed it for me. Thanks!
