### ISSUE TITLE
How do I authenticate?

### ISSUE THREAD

**Issue by KTamas** [nicoSWD/put.io-adder#21]
I start the program and there is no way to authenticate whatsoever...

**Comment by nicoSWD** [comment]
Hey @KTamas!

When you open the app, it should open your default browser and go to put.io for authentication. Once you've put your username and password there, and allowed access to the app, it should work.

Let me know if you're still having trouble with this.

**Comment by KTamas** [comment]
@nicoSWD it doesn't do that.

**Comment by KTamas** [comment]
@nicoSWD okay, so I had an old key in my keychain from the app, since then i had a new account/password but it was trying with the old one. it should detect that somehow I think. once I manually deleted that key from the keychain it worked.

**Comment by nicoSWD** [comment]
Hey @KTamas! Thanks for the suggestion, I'll look into this. I'm glad you sorted it out for now.

😀

**Comment by mjw56** [comment]
Hi, I'm running into this issue on Mac El Capitan in chrome, firefox and safari. I downloaded latest, and also tried with 2.9. I used this app previously, so I deleted the old keychain. When I open the app it opens the site, I click on Authorize Application but it still says Authentication Required in the app.

Any ideas?

**Comment by kaumac** [comment]
I'm having the same issue as @mjw56

**Comment by nicoSWD** [comment]
@mjw56 @kaumac 

Please take a look at the latest release:

https://github.com/nicoSWD/put.io-adder/releases/tag/v3.0.3

This should fix authentication issues.

**Comment by fvdm** [comment]
@nicoSWD I have the same issue with v3.0.3 after deleting and later reinstalling the app.

Only when I delete the old login from the keychain the app runs the authentication successfully.
