### ISSUE TITLE
Cannot authenticate: "Error: Failed to get a..."

### ISSUE THREAD

**Issue by phyllisstein** [nicoSWD/put.io-adder#24]
Hey there! I'm sorry to be a bother, but I'm having a little trouble authenticating the app with my Put.io account. When I open the app, it pops up an "Authorize Application" prompt in my browser, as expected; but when I give it the okay, I see a truncated error message reading "Error: failed to get a". I've tried clearing the app's cookies and caches in my `~/Library` folder, but it didn't seem to help. Any idea what might be going on?

Thanks in advance for your help!

<img width="1440" alt="screen shot 2017-04-07 at 3 03 25 am" src="https://cloud.githubusercontent.com/assets/2207980/24789062/06a5ae12-1b3f-11e7-87bf-a88a8c365fdf.png">

**Comment by ajorpheus** [comment]
@nicoSWD : Please see the fix for this : https://github.com/nicoSWD/put.io-adder/pull/25

**Comment by nicoSWD** [comment]
Thank you very much (to the both of you)!

Your help is much appreciated! I'll look into this very soon!
