### ISSUE TITLE
Difficulty authenticating: token not showing up in callback URL.

### ISSUE THREAD

**Issue by phyllisstein** [nicoSWD/put.io-adder#28]
Hey there! I'm having some trouble authenticating the app with Put.io again. The symptoms are similar to what was reported in #24:

<img width="662" alt="screenshot 3" src="https://user-images.githubusercontent.com/2207980/34911741-7856a15a-f89e-11e7-8395-c2354109b633.png">

The odd thing is that the authentication URL doesn't match the regular expression in #25 because the token isn't being included in the callback. Instead, the authentication page bounces me to this URL:

```
https://api.put.io/v2/oauth2/authenticate?client_id=711&response_type=token&redirect_uri=putio://callback
```

Is it possible that they've changed their login flows again, or am I missing something? Thanks in advance for any thoughts you have!

**Comment by nicoSWD** [comment]
Hey @phyllisstein!

Thanks for letting me know. I'll look into this issue

**Comment by irrg** [comment]
Thought it was just me! 

The Chrome put.io extension is also busted, but nobody seems to have commented about it: https://chrome.google.com/webstore/detail/putio-extension/lmonmjokfiamaoddkeofepnapdldbejb/reviews?hl=en

I probably wouldn't have noticed if I still had an active token, but I got a new computer…

**Comment by altayaydemir** [comment]
Hey guys! We made some changes in our authentication api but it shouldn't be a problem for oauth apps which set/receive callback urls properly.

@nicoSWD I've just cloned the repo and tested out myself and this issue should be resolved if you revert this commit: https://github.com/nicoSWD/put.io-adder/commit/2e35da6ee2b58911e48f517c0ef67d0df1cdef32

we don't add additional parameters that needs to be escaped unless you send a state param on the auth url. in that case the url has a shape like ``putio://callback?state=test#access_token=ABC`` which can be parsed with just ``@"#access_token=(.*)"``

**Comment by nicoSWD** [comment]
@altayaydemir awesome, thank you very much! I'll see if I find some time tonight to push a new build with the fix. 😄

**Comment by irrg** [comment]
Thanks @altayaydemir !

**Comment by altayaydemir** [comment]
@nicoSWD @irrg no worries! (and sorry for the inconvenience 😿)

**Comment by nicoSWD** [comment]
I just pushed a [new release](https://github.com/nicoSWD/put.io-adder/releases/tag/v3.0.4) which should fix authentication issues:

Thanks everyone! :smile:

**Comment by nicoSWD** [comment]
I'm closing this issue for now.

If anyone keeps having problems, please open a new issue!

Thank you all! :smiley:
