### ISSUE TITLE
Unable to open version 3.0.5

### ISSUE THREAD

**Issue by ashleykleynhans** [nicoSWD/put.io-adder#31]
Firstly, thank you for providing this awesome software, it is very much appreciated!

I've updated my Apple Silicon version to 3.0.5 that was released yesterday but can't open it.

It keeps saying that the application needs to be updated by the developer.
I reverted to version 3.0.4 and it works perfectly.

**Comment by nicoSWD** [comment]
Thank you, @ashleykleynhans! Glad people are still using it even though I haven't updated it properly in almost a decade haha.

I set Sonoma 14.5 as minimum version, but I can probably lower it. Not sure if that might be the reason. Which version of macOS are you using?

**Comment by ashleykleynhans** [comment]
I am also on macOS Sonoma 14.5 so I am not sure that the minimum version is the issue.

**Comment by nicoSWD** [comment]
Thank you all for letting me know! Can you try again? @Jackrabbitron @ashleykleynhans 

https://github.com/nicoSWD/put.io-adder/releases/tag/v3.0.5

I've signed the app in a different way now

**Comment by Jackrabbitron** [comment]
@nicoSWD  Works perfectly! I was able to install it no problem and used it to add torrents. Thanks.

**Comment by ashleykleynhans** [comment]
Working perfectly now, thank you again for the awesome software and for fixing it so quickly!

**Comment by nicoSWD** [comment]
Thank you @Jackrabbitron and @ashleykleynhans!
