### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by chris-79** [nicoSWD/put.io-adder#34]
Clicking anywhere above the Name, Status, etc table does nothing (except the open/collapse arrow, which works)

v3.0.5
macOS 14.6.1 (23G93)
M2 MacBook

![CleanShot 2024-08-26 102949@2x](https://github.com/user-attachments/assets/552cff5e-3cc9-40c3-84f7-b0dbd6b97762)

**Comment by nicoSWD** [comment]
Hey @chris-79 

I think this should fix your issue: https://github.com/nicoSWD/put.io-adder/issues/26#issuecomment-309570944

**Comment by chris-79** [comment]
It does! Thanks!
